services:
test_service:
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "5000:5000"
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:5000/" ]
    interval: 30s
    timeout: 10s
    start_period: 5s
    retries: 3
